# yaml-language-server: $schema=./quartz/plugins/quartz-plugins.schema.json
configuration:
  pageTitle: studio
  pageTitleSuffix: ""
  enableSPA: false
  enablePopovers: true
  analytics:
    provider: plausible
  locale: en-US
  baseUrl: vizualizr.github.com/quartz-for-studio
  ignorePatterns:
    - backoffice
    - backoffice/**
    - templates
    - images
    - literatures/**/*.md
    - .obsidian
    - private
  theme:
    fontOrigin: selfHosted
    # cdnCaching: true
    typography: # order of priority: h1 option → header option → theme --h1-font → theme font → Obsidian default
      header: Pretendard GOV Variable
      body: Pretendard GOV Variable
      code: Jetendard
    colors:
      lightMode:
        gray: "rgba(0, 0, 2, 0.5)" # base-content/50 (비활성화 텍스트, 호버 상태 구분선)
        light: "#dfded7" # base-200 (메인 배경)
        lightgray: "#c2c5b9" # base-300 (보조 배경, 테두리, 구분선)
        darkgray: "#000002" # base-content (일반 본문 텍스트)
        dark: "#11083a" # accent (강조 및 헤더 텍스트)
        secondary: "#004b73" # primary (링크, 핵심 인터페이스 액센트, 태그 텍스트)
        tertiary: "#555555" # neutral (링크 호버, 액센트 호버 상태)
        highlight: "rgba(0, 75, 115, 0.08)" # primary 기반 8% 투명도 (태그 배경, 활성화 내비 배경)
        textHighlight: "rgba(158, 214, 237, 0.5)" # info 기반 50% 투명도 (마크다운 텍스트 하이라이트 배경)
      darkMode:
        gray: "rgba(218, 217, 211, 0.5)" # base-100 (메인 배경)
        light: "#212320" # base-200 (보조 배경, 테두리, 구분선)
        lightgray: "#2d2f2b" # base-300 (비활성화 텍스트, 호버 상태 구분선)
        darkgray: "rgba(218, 217, 211, 1)" # base-content (일반 본문 텍스트)
        dark: "#dbd9d0" # --accent-content (강조 및 헤더 텍스트)
        secondary: "#c9c7c2" # primary (링크, 핵심 인터페이스 액센트, 태그 텍스트)
        tertiary: "#5c5e6b" # secondary (링크 호버, 액센트 호버 상태)
        highlight: "rgba(201, 199, 194, 0.08)" # primary 기반 15% 투명도 (태그 배경, 활성화 내비 배경)
        textHighlight: "rgba(56, 78, 89, 0.5)" # info 기반 50% 투명도 (마크다운 텍스트 하이라이트 배경)
plugins:
  - source: "@quartz-community/created-modified-date"
    enabled: true
    options:
      defaultDateType: modified
      priority:
        - frontmatter
        - filesystem
    order: 10
  - source: "@quartz-community/syntax-highlighting"
    enabled: true
    options:
      theme:
        light: github-light
        dark: github-dark
      keepBackground: false
    order: 20
  - source: "@quartz-community/obsidian-flavored-markdown"
    enabled: true
    options:
      comments: true
      highlight: true
      wikilinks: true
      callouts: true
      mermaid: true
      parseTags: true
      parseArrows: true
      parseBlockReferences: true
      enableInHtmlEmbed: false
      enableYouTubeEmbed: true
      enableVideoEmbed: true
      enableCheckbox: true
    order: 30
  - source: "@quartz-community/github-flavored-markdown"
    enabled: true
    order: 40
  - source: "@quartz-community/table-of-contents"
    enabled: true
    order: 50
    layout:
      position: right
      priority: 30
  - source: "@quartz-community/crawl-links"
    enabled: true
    options:
      markdownLinkResolution: absolute
    order: 60
  - source: "@quartz-community/description"
    enabled: true
    order: 70
  - source: "@quartz-community/latex"
    enabled: true
    options:
      renderEngine: katex
    order: 80
  - source: "@quartz-community/citations"
    enabled: false
    order: 85
  - source: "@quartz-community/hard-line-breaks"
    enabled: true
    order: 90
  - source: "@quartz-community/ox-hugo"
    enabled: false
    order: 91
  - source: "@quartz-community/roam"
    enabled: false
    order: 92
  - source: "@quartz-community/quartz-fonts"
    enabled: true
    options:
      fontOrigin: selfHosted
  - source: "@quartz-themes/core"
    enabled: false
    options:
      theme: default
      mode: both
  - source: "@quartz-community/remove-draft"
    enabled: true
  - source: "@quartz-community/explicit-publish"
    enabled: false
  - source: "@quartz-community/unlisted-pages"
    enabled: true
    options: {}
    order: 45
  - source: "@quartz-community/encrypted-pages"
    enabled: true
    options:
      iterations: 600000
      passwordField: password
      unlistWhenEncrypted: false
      outputPath: static/encryptedContentIndex.json
  - source: "@quartz-community/stacked-pages"
    enabled: false
    layout:
      position: afterBody
      priority: 50
      display: all
  - source: "@quartz-community/alias-redirects"
    enabled: true
  - source: "@quartz-community/content-index"
    enabled: true
    options:
      enableSiteMap: true
      enableRSS: true
  - source: "@quartz-community/favicon"
    enabled: true
  - source: "@quartz-community/og-image"
    enabled: true
  - source: "@quartz-community/cname"
    enabled: true
  - source: "@quartz-community/canvas-page"
    enabled: true
  - source: "@quartz-community/content-page"
    enabled: true
  - source: "@quartz-community/folder-page"
    enabled: true
  - source: "@quartz-community/tag-page"
    enabled: true
  - source: "@quartz-community/explorer"
    enabled: true
    options:
      title: notes
      folderDefaultState: collapsed
      folderClickBehavior: link
      useSavedState: true
      mapFn: |
        (node) => {
          # if (node.isFolder) {
          #   node.displayName = "📁 " + node.displayName;
          # } else {
          #   node.displayName = "📄 " + node.displayName;
          # }
          # return node;
        }
      filterFn: |
        (node) => {
          const omit = new Set(["assets"])
          return !omit.has(node.displayName.toLowerCase())
        }
    layout:
      position: left
      priority: 50
  - source: "@quartz-community/graph"
    enabled: true
    layout:
      position: right
      priority: 10
  - source: "@quartz-community/search"
    enabled: true
    layout:
      position: left
      priority: 20
      group: toolbar
      groupOptions:
        grow: true
  - source: "@quartz-community/backlinks"
    enabled: true
    layout:
      position: right
      priority: 50
  - source: "@quartz-community/article-title"
    enabled: true
    layout:
      position: beforeBody
      priority: 10
  - source: "@quartz-community/content-meta"
    enabled: true
    layout:
      position: beforeBody
      priority: 20
  - source: "@quartz-community/tag-list"
    enabled: false
    layout:
      position: beforeBody
      priority: 30
  - source: "@quartz-community/page-title"
    enabled: true
    layout:
      position: left
      priority: 10
  - source: "@quartz-community/darkmode"
    enabled: true
    layout:
      position: left
      priority: 30
      group: toolbar
  - source: "@quartz-community/reader-mode"
    enabled: true
    layout:
      position: left
      priority: 35
      group: toolbar
  - source: "@quartz-community/breadcrumbs"
    enabled: true
    layout:
      position: beforeBody
      priority: 5
      condition: not-index
  - source: "@quartz-community/comments"
    enabled: false
    options:
      provider: giscus
      options: {}
    layout:
      position: afterBody
      priority: 10
  - source: "@quartz-community/footer"
    enabled: true
    options:
      links:
        © o-m.kr: https://o-m.kr
    layout:
      position: footer
      priority: 50
  - source: "@quartz-community/recent-notes"
    enabled: false
    options:
      limit: 5
      # linkToMore: true
  - source: "@quartz-community/spacer"
    enabled: true
    options: {}
    order: 25
    layout:
      position: left
      priority: 25
      display: mobile-only
  - source: "@quartz-community/bases-page"
    enabled: true
    options: {}
    order: 50
  - source: "@quartz-community/note-properties"
    enabled: true
    options:
      includeAll: false
      includedProperties:
        - description
        - tags
        - aliases
      excludedProperties: []
      hidePropertiesView: false
      delimiters: ---
      language: yaml
    order: 5
    layout:
      position: beforeBody
      priority: 15
      display: all
  - source: "@quartz-community/obsidian-plugin-excalidraw"
    enabled: false
    options:
      enableInteraction: true
      darkMode: auto
      exportPadding: 20
    order: 50
layout:
  groups:
    toolbar:
      priority: 35
      direction: row
      gap: 0.5rem
  byPageType:
    "404":
      positions:
        beforeBody: []
        left: []
        right: []
    content: {}
    folder:
      exclude:
        - reader-mode
      positions:
        right: []
    tag:
      exclude:
        - reader-mode
      positions:
        right: []
    canvas: {}
    bases: {}
